name: Atualizar Cotação do Euro

on:
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  update-currency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip3 install requests

      - name: Executar script de cotação
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 EuroValue.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verificar mudanças
        run: |
          if git diff --quiet; then
            echo "Sem alterações, nada para commit."
            exit 0
          fi

      - name: Commit e Push
        run: |
          git add VALUE.txt
          git commit -m "Atualização do valor do Euro"
          git push
