name: Euro Scraper Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos

  workflow_dispatch:  # Permite rodar manualmente se quiser

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Restaurar última cotação do cache
        id: cache-cotacao
        uses: actions/cache@v3
        with:
          path: ultimo_valor.txt
          key: euro-cotacao
          restore-keys: euro-cotacao

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar o bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python EuroScraper.py

      - name: Salvar a última cotação no cache
        if: always()
        run: |
          echo "Cache atualizado com a última cotação."
