name: Euro Value Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # Roda a cada 10 minutos
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar EuroValue Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python EuroValue/EuroValue.py

      - name: Cache da última cotação
        uses: actions/cache@v4
        with:
          path: EuroValue/ultimo_valor.txt
          key: euro-cotacao-${{ github.run_id }}
          restore-keys: euro-cotacao-
