name: Euro Value Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # Roda a cada 10 minutos
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restaurar Cache da Última Cotação
        uses: actions/cache@v4
        with:
          path: EuroValue/ultimo_valor.txt
          key: euro-cotacao-${{ github.run_id }}
          restore-keys: euro-cotacao-

      - name: Instalar dependências
        run: pip install requests

      - name: Criar arquivo de cache, se necessário
        run: |
          if [ ! -f "EuroValue/ultimo_valor.txt" ]; then
            echo "0.00" > EuroValue/ultimo_valor.txt
          fi

      - name: Executar EuroValue Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python EuroValue.py

      - name: Debug Files (ver arquivos gerados)
        run: ls -R EuroValue
